name: Unit Tests
on:
  pull_request:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          extensions: mysql
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Test with PHPUnit
        run: ./vendor/bin/phpunit --coverage-clover .qodana/code-coverage/clover.xml
        env:
          XDEBUG_MODE: coverage

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: .qodana/code-coverage

      - name: Upload to Qodana
        uses: jetbrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: "--linter,jetbrains/qodana-php:latest"
